#include "PostProcessor.h"

#include <sstream>
#include <iomanip>
#include <cmath>
#include <algorithm>

namespace PathForge::Post {

PostProcessor::PostProcessor() = default;

PostProcessor::PostProcessor(const NCConfig& config) : m_config(config) {}

std::string PostProcessor::generate(const Path::ToolpathList& toolpaths, const NCConfig& config) {
    std::string result;
    for (size_t i = 0; i < toolpaths.size(); ++i) {
        if (i > 0) {
            result += "\n";
        }
        result += generate(*toolpaths[i], config);
    }
    return result;
}

bool PostProcessor::validate(const Path::Toolpath& toolpath) const {
    return getValidationErrors(toolpath).empty();
}

std::vector<std::string> PostProcessor::getValidationErrors(const Path::Toolpath& toolpath) const {
    std::vector<std::string> errors;

    if (toolpath.isEmpty()) {
        errors.push_back("Toolpath is empty");
        return errors;
    }

    for (size_t i = 0; i < toolpath.pointCount(); ++i) {
        const auto& point = toolpath.points()[i];

        if (std::isnan(point.position.X()) || std::isnan(point.position.Y()) || std::isnan(point.position.Z())) {
            errors.push_back("Point " + std::to_string(i) + " has NaN coordinates");
        }

        if (std::isinf(point.position.X()) || std::isinf(point.position.Y()) || std::isinf(point.position.Z())) {
            errors.push_back("Point " + std::to_string(i) + " has infinite coordinates");
        }

        if (point.feedrate < 0) {
            errors.push_back("Point " + std::to_string(i) + " has negative feedrate");
        }

        if (point.spindleSpeed < 0) {
            errors.push_back("Point " + std::to_string(i) + " has negative spindle speed");
        }
    }

    return errors;
}

GCodePostProcessor::GCodePostProcessor() = default;

GCodePostProcessor::GCodePostProcessor(const NCConfig& config) : PostProcessor(config) {}

std::string GCodePostProcessor::generate(const Path::Toolpath& toolpath, const NCConfig& config) {
    m_config = config;
    m_outputLines.clear();
    m_lineNumber = config.startLineNumber;
    m_firstPoint = true;

    std::string header = generateHeader(toolpath, config);
    std::string toolpathCode = generateToolpath(toolpath, config);
    std::string footer = generateFooter(config);

    return header + toolpathCode + footer;
}

std::string GCodePostProcessor::generateHeader(const Path::Toolpath& toolpath, const NCConfig& config) {
    std::ostringstream header;

    header << "%\n";

    header << "(" << config.programNumber << " " << config.programName << ")\n";

    if (config.outputComments) {
        header << "(Generated by PathForge PostProcessor)\n";
        header << "(Date: " << __DATE__ << " " << __TIME__ << ")\n";

        if (!toolpath.name().empty()) {
            header << "(Toolpath: " << toolpath.name() << ")\n";
        }

        if (config.toolDiameter > 0) {
            header << "(Tool: " << config.toolDiameter << "mm " << config.toolName << ")\n";
        }
    }

    if (config.outputToolChange) {
        header << "N" << m_lineNumber << " T" << config.toolNumber << " M06\n";
        m_lineNumber += config.lineNumberIncrement;
    }

    if (config.outputSpindle && config.defaultSpindleSpeed > 0) {
        header << "N" << m_lineNumber << " S" << config.defaultSpindleSpeed << " M03\n";
        m_lineNumber += config.lineNumberIncrement;
    }

    if (config.workCoordinateSystem >= 54 && config.workCoordinateSystem <= 59) {
        header << "N" << m_lineNumber << " G" << config.workCoordinateSystem << "\n";
        m_lineNumber += config.lineNumberIncrement;
    }

    header << "N" << m_lineNumber << " " << (config.absoluteMode ? "G90" : "G91") << "\n";
    m_lineNumber += config.lineNumberIncrement;

    header << "N" << m_lineNumber << " " << (config.metricMode ? "G21" : "G20") << "\n";
    m_lineNumber += config.lineNumberIncrement;

    header << "N" << m_lineNumber << " G40 G49 G80\n";
    m_lineNumber += config.lineNumberIncrement;

    return header.str();
}

std::string GCodePostProcessor::generateFooter(const NCConfig& config) {
    std::ostringstream footer;

    footer << "N" << m_lineNumber << " M05\n";
    m_lineNumber += config.lineNumberIncrement;

    footer << "N" << m_lineNumber << " G00 Z" << std::fixed << std::setprecision(config.decimalPlaces) << config.safeZ << "\n";
    m_lineNumber += config.lineNumberIncrement;

    footer << "N" << m_lineNumber << " M30\n";
    footer << "%\n";

    return footer.str();
}

std::string GCodePostProcessor::generateToolpath(const Path::Toolpath& toolpath, const NCConfig& config) {
    std::ostringstream output;
    const auto& points = toolpath.points();

    for (size_t i = 0; i < points.size(); ++i) {
        const auto& point = points[i];

        switch (point.moveType) {
            case Path::MoveType::Rapid:
                output << formatRapidMove(point, config) << "\n";
                break;
            case Path::MoveType::Linear:
                output << formatLinearMove(point, config) << "\n";
                break;
            case Path::MoveType::ArcCW:
            case Path::MoveType::ArcCCW:
                if (i > 0) {
                    output << formatArcMove(points[i - 1], point, config) << "\n";
                }
                break;
            case Path::MoveType::Helix:
                if (i > 0) {
                    output << formatHelix(points[i - 1], point, config) << "\n";
                }
                break;
            case Path::MoveType::Dwell:
                output << "N" << m_lineNumber << " G04 P" << std::fixed << std::setprecision(3) << point.feedrate << "\n";
                m_lineNumber += config.lineNumberIncrement;
                break;
        }

        m_lastPoint = point;
        m_firstPoint = false;
    }

    return output.str();
}

std::string GCodePostProcessor::formatLinearMove(const Path::PathPoint& point, const NCConfig& config) {
    std::ostringstream line;

    if (config.lineNumbers) {
        line << "N" << m_lineNumber << " ";
        m_lineNumber += config.lineNumberIncrement;
    }

    line << "G01" << formatCoordinate(point.position.X(), point.position.Y(), point.position.Z(), config);

    if (point.feedrate > 0) {
        line << formatFeedrate(point.feedrate, config);
    }

    if (config.outputSpindle && point.spindleSpeed > 0) {
        line << " S" << static_cast<int>(point.spindleSpeed);
    }

    return line.str();
}

std::string GCodePostProcessor::formatRapidMove(const Path::PathPoint& point, const NCConfig& config) {
    std::ostringstream line;

    if (config.lineNumbers) {
        line << "N" << m_lineNumber << " ";
        m_lineNumber += config.lineNumberIncrement;
    }

    line << "G00" << formatCoordinate(point.position.X(), point.position.Y(), point.position.Z(), config);

    return line.str();
}

std::string GCodePostProcessor::formatArcMove(const Path::PathPoint& from, const Path::PathPoint& to,
                                                const NCConfig& config) {
    std::ostringstream line;

    if (config.lineNumbers) {
        line << "N" << m_lineNumber << " ";
        m_lineNumber += config.lineNumberIncrement;
    }

    bool isCW = to.moveType == Path::MoveType::ArcCW;
    line << (isCW ? "G02" : "G03");

    double i = (to.position.X() - from.position.X()) / 2.0;
    double j = (to.position.Y() - from.position.Y()) / 2.0;
    double k = (to.position.Z() - from.position.Z()) / 2.0;

    line << formatCoordinate(to.position.X(), to.position.Y(), to.position.Z(), config);
    line << " I" << std::fixed << std::setprecision(config.decimalPlaces) << i;
    line << " J" << std::fixed << std::setprecision(config.decimalPlaces) << j;
    line << " K" << std::fixed << std::setprecision(config.decimalPlaces) << k;

    if (to.feedrate > 0) {
        line << formatFeedrate(to.feedrate, config);
    }

    return line.str();
}

std::string GCodePostProcessor::formatHelix(const Path::PathPoint& from, const Path::PathPoint& to,
                                              const NCConfig& config) {
    std::ostringstream line;

    bool isCW = to.moveType == Path::MoveType::ArcCW;

    line << "N" << m_lineNumber << " " << (isCW ? "G02" : "G03");
    m_lineNumber += config.lineNumberIncrement;

    double i = (to.position.X() - from.position.X()) / 2.0;
    double j = (to.position.Y() - from.position.Y()) / 2.0;

    line << formatCoordinate(to.position.X(), to.position.Y(), from.position.Z(), config);
    line << " I" << std::fixed << std::setprecision(config.decimalPlaces) << i;
    line << " J" << std::fixed << std::setprecision(config.decimalPlaces) << j;
    if (to.feedrate > 0) {
        line << formatFeedrate(to.feedrate, config);
    }
    line << "\n";

    line << "N" << m_lineNumber << " G01 Z" << std::fixed << std::setprecision(config.decimalPlaces) << to.position.Z();
    m_lineNumber += config.lineNumberIncrement;
    if (to.feedrate > 0) {
        line << formatFeedrate(to.feedrate, config);
    }

    return line.str();
}

std::string GCodePostProcessor::formatCoordinate(double x, double y, double z, const NCConfig& config) {
    std::ostringstream coord;
    coord << std::fixed << std::setprecision(config.decimalPlaces);
    coord << " X" << x << " Y" << y << " Z" << z;
    return coord.str();
}

std::string GCodePostProcessor::formatFeedrate(double feedrate, const NCConfig& config) {
    std::ostringstream feed;
    feed << " F" << std::fixed << std::setprecision(config.decimalPlaces) << feedrate;
    return feed.str();
}

std::string GCodePostProcessor::formatSpindleSpeed(int rpm, const NCConfig& config) {
    std::ostringstream spindle;
    spindle << " S" << rpm;
    return spindle.str();
}

void GCodePostProcessor::addComment(const std::string& comment) {
    if (m_config.outputComments) {
        m_outputLines.push_back("(" + comment + ")");
    }
}

void GCodePostProcessor::addLine(const std::string& line) {
    if (!line.empty()) {
        m_outputLines.push_back(line);
    }
}

}
